trigger:
  - main
 
pool:
  vmImage: ubuntu-latest
 
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18"
    displayName: "Install Node.js"
 
  - script: npm ci
    displayName: "Install dependencies"
 
  - script: |
      npx cross-env ENV=qa BROWSER=chrome HEADLESS=true npm run test:smoke
    displayName: "Run Smoke Tests"